name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform fmt
        run: terraform fmt -recursive -check

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
